import { useEffect, useMemo, useState } from "react";
import type { ApiAnalysisAdapter, ApiCatalogItem, ApiComparisonView, ApiSelection, ApiStatus } from "./dataSource/apiAnalysisAdapter";

interface Props { adapter: ApiAnalysisAdapter; status: ApiStatus; }
const monthInput = (value: string) => `${value.slice(0, 4)}-${value.slice(4)}`;
const monthPayload = (value: string) => value.replace("-", "");
const label = (selection: ApiSelection) => selection.item_name_id ? `${selection.item_group_id} / ${selection.item_name_id}` : selection.item_group_id;
const display = (value: unknown) => typeof value === "string" ? value : value === null || value === undefined ? "—" : String(value);

export default function ApiModeApp({ adapter, status }: Props) {
  const [groupQuery, setGroupQuery] = useState(""); const [groups, setGroups] = useState<ApiCatalogItem[]>([]); const [selectedGroup, setSelectedGroup] = useState<string | null>(null);
  const [nameQuery, setNameQuery] = useState(""); const [names, setNames] = useState<ApiCatalogItem[]>([]); const [selections, setSelections] = useState<ApiSelection[]>([]);
  const [start, setStart] = useState(monthInput(status.period_start)); const [end, setEnd] = useState(monthInput(status.period_end)); const [view, setView] = useState<ApiComparisonView | null>(null);
  const [state, setState] = useState<"idle" | "loading" | "error" | "policy_pending" | "empty">("policy_pending"); const [message, setMessage] = useState("Local internal-only API. Public release policy is not approved.");
  useEffect(() => { const timer = window.setTimeout(() => { void adapter.itemGroups(groupQuery).then(setGroups).catch(() => { setState("error"); setMessage("Catalog request failed. Check the local API without exposing internal details."); }); }, 250); return () => window.clearTimeout(timer); }, [adapter, groupQuery]);
  useEffect(() => { if (!selectedGroup) { setNames([]); return; } const timer = window.setTimeout(() => { void adapter.itemNames(selectedGroup, nameQuery).then(setNames).catch(() => { setState("error"); setMessage("Parent-scoped item-name request failed."); }); }, 250); return () => window.clearTimeout(timer); }, [adapter, selectedGroup, nameQuery]);
  const invalidPeriod = !start || !end || start > end || ((Number(end.slice(0, 4)) - Number(start.slice(0, 4))) * 12 + Number(end.slice(5)) - Number(start.slice(5)) + 1 > 36);
  const canRun = selections.length > 0 && selections.length <= 10 && !invalidPeriod;
  const selectedKeys = useMemo(() => new Set(selections.map((item) => `${item.selection_type}:${item.item_group_id}:${item.item_name_id ?? ""}`)), [selections]);
  function add(selection: ApiSelection) { const key = `${selection.selection_type}:${selection.item_group_id}:${selection.item_name_id ?? ""}`; if (!selectedKeys.has(key) && selections.length < 10) setSelections((current) => [...current, selection]); }
  async function run(): Promise<void> { if (!canRun) return; setState("loading"); setMessage("Loading verified local aggregate observations."); try { const next = await adapter.compare(monthPayload(start), monthPayload(end), selections); setView(next); setState(next.product_month.length || next.item_group_month.length ? "idle" : "empty"); setMessage(next.product_month.length || next.item_group_month.length ? "Local aggregate comparison loaded. Public release policy remains not approved." : "No aggregate observations matched this selection and period."); } catch { setState("error"); setMessage("Comparison request failed or was rejected by the local API."); } }
  return <main id="main-content" className="app-shell" tabIndex={-1}>
    <header className="hero"><p className="eyebrow">LOCAL INTERNAL ONLY</p><h1>Class 3 comparison</h1><p className="hero-lead">Verified serving-mart aggregates through the localhost API. This is not a public service or public-data release.</p></header>
    <div className="state-notice state-attention" role="status" aria-live="polite"><strong>local_internal_only</strong><span>{message}</span><span>public_release_policy: not_approved</span></div>
    <section className="search-panel" aria-labelledby="api-search-heading"><div className="section-heading"><p className="section-kicker">Local API selection</p><h2 id="api-search-heading">Item group and parent-scoped item name</h2></div>
      <label className="search-label">Item group search<input type="search" value={groupQuery} onChange={(event) => setGroupQuery(event.target.value)} /></label>
      <ul className="search-results" aria-label="item group suggestions">{groups.map((item) => <li key={item.item_group_id}><button type="button" onClick={() => { setSelectedGroup(item.item_group_id); add({ selection_type: "item_group", item_group_id: item.item_group_id }); }}>{item.item_group_id}</button></li>)}</ul>
      {selectedGroup && <><label className="search-label">Item name within {selectedGroup}<input type="search" value={nameQuery} onChange={(event) => setNameQuery(event.target.value)} /></label><ul className="search-results" aria-label="parent scoped item name suggestions">{names.map((item) => <li key={item.item_name_id}><button type="button" onClick={() => add({ selection_type: "item_name", item_group_id: selectedGroup, item_name_id: item.item_name_id })}>{item.item_name_id}</button></li>)}</ul></>}
    </section>
    <div className="filter-strip"><section className="selection-panel"><h2>Selections ({selections.length}/10)</h2><ul className="selection-list">{selections.map((item) => <li key={`${item.selection_type}:${label(item)}`}><span>{label(item)}</span><button type="button" onClick={() => setSelections((current) => current.filter((entry) => entry !== item))}>Remove</button></li>)}</ul></section><section className="period-panel"><h2>Period</h2><label>Start<input type="month" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>End<input type="month" value={end} onChange={(event) => setEnd(event.target.value)} /></label>{invalidPeriod && <p className="field-error" role="alert">Use an in-range period of no more than 36 months.</p>}<button type="button" className="period-apply" disabled={!canRun || state === "loading"} onClick={() => void run()}>Apply comparison</button></section></div>
    {view && <><section className="results-section"><div className="section-heading section-heading--rule"><p className="section-kicker">Monthly aggregates</p><h2>Comparison results</h2></div><div className="card-grid">{[...view.product_month, ...view.item_group_month].map((row, index) => <article className="result-card" key={`${String(row.month)}:${index}`}><h3>{display(row.month)} · {display(row.product_id ?? row.item_group_id)}</h3><dl className="released-content"><div><dt>Transactions</dt><dd>{display(row.tx_count)}</dd></div><div><dt>Amount</dt><dd>{display(row.amount_sum_clean)}</dd></div><div><dt>Raw quantity</dt><dd>{display(row.raw_supply_qty_sum)}</dd></div><div><dt>Piece quantity</dt><dd>{display(row.piece_qty_sum)}</dd></div></dl></article>)}</div></section><section className="coverage-section"><h2>Coverage and endpoint composition</h2><p>Endpoint values are aggregate dimensions; raw endpoint identifiers are not displayed.</p><ul className="reach-list">{view.endpoint_composition.map((row, index) => <li key={index}><span>{display(row.month)} · {display(row.dimension)}</span><span>{display(row.dimension_value)} · {display(row.entity_count_distinct)}</span></li>)}</ul><ul className="coverage-grid">{view.coverage.map((row, index) => <li key={index}>{display(row.month)} · amount {display(row.amount_sum_clean)} · observation count {display(row.aggregate_observation_count)}</li>)}</ul></section></>}
    {state === "empty" && <p className="empty-copy empty-copy--prominent">No aggregate observations are available for the selected local query.</p>}
  </main>;
}
