import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import App from "./App";
import { validatePayloads } from "./dataSource";
const service = { analysis_schema_version: "1.0.0", run_status: "completed", service_results: [{ entity_id: "a", anchor_month: "202406", window_months: ["202404","202405","202406"], model: "gadnr", model_version: "v", role_group: "distributor", role_group_sample_size: 3, review_priority_percentile: 50, insufficient_sample: false, reason: null, graph_summary: { node_count: 2, edge_count: 1, self_loop_count: 0 }, previous_anchor_diff: { new_counterparty_ids: ["b"] }, prior_nonoverlap_3m_diff: { amount_change: "1" }, bc_evidence: { gateway_share: "0.5", mode: "exact" } }] };
const graph = { graph_scope: "one_hop", selected_entity_id: "a", anchor_month: "202406", window_months: ["202404","202405","202406"], nodes: [{entity_id:"a",selected:true,role_group:"distributor",region:"11",region_missing_or_conflict:false},{entity_id:"b",selected:false,role_group:"hospital",region:"26",region_missing_or_conflict:false}], edges: [{src_company_id:"a",dst_company_id:"b",tx_count:1,unique_product_count:1,active_month_count:1,amount_sum_clean:"1.000000",amount_valid_row_count:1,amount_valid_rate:"1.000000",raw_supply_qty_sum:"2.000000",raw_supply_qty_valid_row_count:1,raw_supply_qty_valid_rate:"1.000000",piece_qty_sum:"3.000000",piece_qty_valid_row_count:1,piece_qty_valid_rate:"1.000000"}], graph_summary:{selected_node_count:1,one_hop_counterparty_count:1,edge_count:1,self_loop_excluded_count:0,truncated:false,truncation_reason:null} };
describe("Class 1 local monitor", () => { it("validates matching local payloads and never exposes raw scores", () => { expect(validatePayloads(service, graph).graph.selected_entity_id).toBe("a"); expect(() => validatePayloads(service, {...graph, selected_entity_id:"b"})).toThrow(/selected node/); expect(() => validatePayloads({...service, raw_score: 1}, graph)).toThrow(/raw_score/); }); it("renders edge details without combining quantities", async () => { vi.stubEnv("VITE_CLASS1_DATA_SOURCE", "local"); vi.stubEnv("VITE_CLASS1_SERVICE_URL", "/service"); vi.stubEnv("VITE_CLASS1_GRAPH_URL", "/graph"); vi.stubGlobal("fetch", vi.fn((url: string) => Promise.resolve({ ok: true, json: () => Promise.resolve(url === "/service" ? service : graph) })) as unknown as typeof fetch); render(<App />); expect((await screen.findAllByText("선택 업체")).length).toBeGreaterThan(0); expect(screen.getByText("원시 공급수량 / 유효 건수 / coverage")).toBeInTheDocument(); expect(document.body.textContent).not.toContain("raw_score"); }); it("shows explicit failure rather than a mock fallback", async () => { vi.stubEnv("VITE_CLASS1_DATA_SOURCE", "local"); vi.stubEnv("VITE_CLASS1_SERVICE_URL", ""); vi.stubEnv("VITE_CLASS1_GRAPH_URL", ""); render(<App />); expect(await screen.findByText(/표시할 수 없습니다/)).toBeInTheDocument(); }); });

describe("insufficient graph local artifact", () => { it("loads as a score-free dedicated state", async () => { const insufficientService = { analysis_schema_version: "1.0.0", run_status: "insufficient_graph", service_results: [] }; vi.stubEnv("VITE_CLASS1_DATA_SOURCE", "local"); vi.stubEnv("VITE_CLASS1_SERVICE_URL", "/service"); vi.stubEnv("VITE_CLASS1_GRAPH_URL", "/graph"); vi.stubGlobal("fetch", vi.fn((url: string) => Promise.resolve({ ok: true, json: () => Promise.resolve(url === "/service" ? insufficientService : graph) })) as unknown as typeof fetch); render(<App />); expect(await screen.findByText("관계망이 충분하지 않습니다")).toBeInTheDocument(); expect(document.body.textContent).not.toContain("raw_score"); }); });
