import { useEffect, useState } from "react";
import type { GraphEdge } from "./contracts";
import { loadLocal, type LoadState } from "./dataSource";

const display = (value: string | null) => value ?? "검증된 값 없음";
function EdgeDetail({ edge }: { edge: GraphEdge }) { return <aside className="edge-detail"><h3>선택한 거래 관계 상세</h3><p>{edge.src_company_id} → {edge.dst_company_id}</p><dl><div><dt>거래 건수</dt><dd>{edge.tx_count}</dd></div><div><dt>고유 품목 수</dt><dd>{edge.unique_product_count}</dd></div><div><dt>활성 월 수</dt><dd>{edge.active_month_count}</dd></div><div><dt>금액 / 유효 건수 / coverage</dt><dd>{display(edge.amount_sum_clean)} / {edge.amount_valid_row_count} / {display(edge.amount_valid_rate)}</dd></div><div><dt>원시 공급수량 / 유효 건수 / coverage</dt><dd>{display(edge.raw_supply_qty_sum)} / {edge.raw_supply_qty_valid_row_count} / {display(edge.raw_supply_qty_valid_rate)}</dd></div><div><dt>낱개수량 / 유효 건수 / coverage</dt><dd>{display(edge.piece_qty_sum)} / {edge.piece_qty_valid_row_count} / {display(edge.piece_qty_valid_rate)}</dd></div></dl></aside>; }
function Header({ entity, anchor, months, status }: { entity: string; anchor: string; months: string[]; status: string }) { return <><header className="hero"><p className="eyebrow">NIDS · CLASS 1</p><h1>내부 거래 관계 모니터링</h1><p>로컬 분석 데이터 · 내부 전용 · 공개 정책 미적용</p></header><section className="status"><strong>선택 업체</strong><span className="id">{entity}</span><span>anchor {anchor} · 분석 구간 {months.join(" ~ ")}</span><span>상태: {status}</span></section></>; }
function Ready({ state }: { state: Extract<LoadState, { kind: "ready" }> }) {
  const { graph, service } = state;
  const [selectedEdge, setSelectedEdge] = useState<GraphEdge | null>(graph.edges[0] ?? null);
  if (service.run_status === "insufficient_graph") return <main id="main-content" className="shell" tabIndex={-1}><Header entity={graph.selected_entity_id} anchor={graph.anchor_month} months={graph.window_months} status={service.run_status} /><section className="empty-state"><h2>관계망이 충분하지 않습니다</h2><p>정상 local 분석 산출물에는 모델 점수와 service 결과가 없으므로 score-free 안내만 표시합니다.</p><p>다른 업체를 보려면 offline runner를 해당 업체 ID로 다시 실행하십시오.</p></section></main>;
  const row = service.service_results.find(item => item.entity_id === graph.selected_entity_id)!;
  const inbound = graph.nodes.filter(node => !node.selected && graph.edges.some(edge => edge.src_company_id === node.entity_id && edge.dst_company_id === row.entity_id));
  const outbound = graph.nodes.filter(node => !node.selected && graph.edges.some(edge => edge.src_company_id === row.entity_id && edge.dst_company_id === node.entity_id));
  const bc = row.bc_evidence;
  return <main id="main-content" className="shell" tabIndex={-1}><Header entity={row.entity_id} anchor={row.anchor_month} months={row.window_months} status={service.run_status} /><section className="summary"><article><h2>검토 우선순위</h2><p>{row.insufficient_sample ? "역할군 표본 부족" : `${row.review_priority_percentile ?? "—"} percentile`}</p><small>역할군 {row.role_group} · 표본 {row.role_group_sample_size}</small></article><article><h2>관계망 범위</h2><p>1-hop 직접 거래 관계</p><small>거래처 {graph.graph_summary.one_hop_counterparty_count} · edge {graph.graph_summary.edge_count}</small></article></section><section className="graph-section"><h2>선택 업체 중심 1-hop 관계망</h2><div className="graph"><div className="lane"><h3>Inbound</h3>{inbound.map(node => <span className="node" key={node.entity_id}>{node.entity_id}<small>{node.role_group}</small></span>)}</div><div className="lane selected"><h3>선택 업체</h3><span className="node is-selected">{row.entity_id}<small>{row.role_group}</small></span></div><div className="lane"><h3>Outbound</h3>{outbound.map(node => <span className="node" key={node.entity_id}>{node.entity_id}<small>{node.role_group}</small></span>)}</div></div><ul className="edge-list">{graph.edges.map(edge => <li key={`${edge.src_company_id}-${edge.dst_company_id}`}><button type="button" onClick={() => setSelectedEdge(edge)}>{edge.src_company_id} → {edge.dst_company_id}</button></li>)}</ul>{selectedEdge && <EdgeDetail edge={selectedEdge} />}</section><section className="details"><article><h2>BC 보조지표</h2><p>gateway share: {String(bc.gateway_share ?? "없음")}</p><p>reachable pair / target: {String(bc.reachable_source_target_pairs ?? "없음")} / {String(bc.reachable_target_count ?? "없음")}</p><p>component size / mode: {String(bc.weak_component_size ?? "없음")} / {String(bc.mode ?? "없음")}</p></article><article><h2>관계·기간 diff 보조지표</h2><p>직전 앵커 신규: {String(row.previous_anchor_diff.new_counterparty_ids ?? "없음")}</p><p>비중첩 3개월 금액 변화: {String(row.prior_nonoverlap_3m_diff.amount_change ?? "없음")}</p></article></section><footer>다른 업체를 보려면 offline runner를 해당 업체 ID로 다시 실행하십시오.</footer></main>;
}
export default function App() { const [state, setState] = useState<LoadState>({ kind: "loading" }); useEffect(() => { void loadLocal().then(setState); }, []); return <><a className="skip" href="#main-content">본문으로 건너뛰기</a>{state.kind === "loading" ? <main className="shell"><p>로컬 분석 데이터를 준비하는 중입니다.</p></main> : state.kind === "error" ? <main id="main-content" className="shell empty-state" tabIndex={-1}><h1>내부 분석 데이터를 표시할 수 없습니다</h1><p>{state.message}</p></main> : <Ready state={state} />}</>; }
